# Generated by Django 4.2.3 on 2023-07-14 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(default=datetime.date(2023, 7, 14))),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
